
# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghibli-art-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghibli-art
  template:
    metadata:
      labels:
        app: ghibli-art
    spec:
      containers:
      - name: ghibli-art
        image: ghibli-art-converter:latest
        ports:
        - containerPort: 5000


